"""empty message

Revision ID: 437298d1a16c
Revises: 5747869d0ecb
Create Date: 2025-04-19 13:54:32.541630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437298d1a16c'
down_revision = '5747869d0ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
